Add category model
OlegAvanesov/main-spring-project pull request #10
Opened 2024-02-16 20:40 UTC by OlegAvanesov

2024-02-17 12:27 UTC, okuzan requested changes
minor fixes

2024-02-17 12:27 UTC, okuzan commented on src/main/java/mate/academy/mainspringproject/mappers/CategoryMapper.java
> +
```suggestion
```

2024-02-17 12:27 UTC, okuzan commented on src/main/java/mate/academy/mainspringproject/mappers/CategoryMapper.java
> +
```suggestion
```

2024-02-17 12:27 UTC, okuzan commented on src/main/java/mate/academy/mainspringproject/model/Book.java
>      private Boolean isDeleted = false;
```suggestion
    private boolean isDeleted = false;
```
I'm not sure NULL would make sense here

2024-02-17 12:27 UTC, okuzan commented on src/main/java/mate/academy/mainspringproject/model/Category.java
> +@SQLRestriction("is_deleted = false")
TRUE and FALSE

2024-02-17 12:27 UTC, okuzan commented on src/main/java/mate/academy/mainspringproject/model/Category.java
> +@SQLDelete(sql = "UPDATE categories SET is_deleted = true WHERE id=?")
```suggestion
@SQLDelete(sql = "UPDATE categories SET is_deleted = true WHERE id = ?")
```

2024-02-17 12:27 UTC, okuzan commented on src/main/java/mate/academy/mainspringproject/repository/book/BookRepository.java
> +
```suggestion
```

2024-02-17 12:27 UTC, okuzan commented on src/main/java/mate/academy/mainspringproject/service/user/UserServiceImpl.java
> +                .findFirst().orElseThrow(
```suggestion
                .findFirst()
                .orElseThrow(
```

2024-02-17 12:27 UTC, okuzan commented on src/main/java/mate/academy/mainspringproject/service/category/CategoryService.java
> +
```suggestion
```

2024-02-18 11:20 UTC, MentorMA approved these changes

2024-02-18 22:20 UTC, merged